version: '3.0'
services:
  ocserv:
    image: ocserv:1.1.6
    restart: always
    container_name: ocserv
    privileged: true
    ports:
      - 443:443/udp
      - 443:443
    volumes:
      - "/etc:etc" #use host user
    # environment:
    #   - CA_CN=VPN CA
    #   - CA_ORG=Big Corp
    #   - CA_DAYS=9999
    #   - SRV_CN=www.example.com
    #   - SRV_ORG=My Company
    #   - SRV_DAYS=9999
